### ISSUE TITLE
additional example ?

### ISSUE THREAD

**Issue by Nick-Mul** [basf/MolPipeline#4]
Hi this looks really useful and very easy to use. I am sure this should be obvious but the notebook ends with:

```Instead of training a machine learning model, we can also compose the elements to make a pipeline that computes the molecular fingerprint matrix.```

this is exactly want I want to do, do you mind give an example of how do output this to file ? 

Many thanks,
Nick

**Comment by c-w-feldmann** [comment]
Hi @Nick-Mul ,

For a simple pipeline returning the Morgan Fingerprint it would look like this:
```python
from molpipeline import Pipeline
from molpipeline.any2mol import AutoToMol
from molpipeline.mol2any import MolToMorganFP

pipeline = Pipeline(
    [
        ("auto2mol", AutoToMol()),
        ("morgan_fp", MolToMorganFP),
    ]
)

pipeline.fit_transform(your_smiles_list)
```

The default parameter for `MolToMorganFP` is `return_as=sparse` which will return the fingerprints as `scipy.sparse.csr_martix`. Other options would be `dense` or `explicit_bit_vect`, which will return a numpy array or a list of [rdkit ExplicitBitVect](https://www.rdkit.org/docs/source/rdkit.DataStructs.cDataStructs.html#rdkit.DataStructs.cDataStructs.ExplicitBitVect), respectively.

I hope this answers your Question.

Christian

**Comment by Nick-Mul** [comment]
Thanks Christian, that's perfect!
